const report = require('multiple-cucumber-html-reporter');
const fs = require('fs-extra');
const path = require('path');

/**
 * Generate HTML Report
 * Creates a professional HTML report from Cucumber JSON output
 */
function generateReport() {
  const jsonFile = path.join(process.cwd(), 'reports', 'generated', 'cucumber-report.json');
  const generatedDir = path.join(process.cwd(), 'reports', 'generated');
  
  // Check if JSON report exists
  if (!fs.existsSync(jsonFile)) {
    console.error('ERROR: Cucumber JSON report not found at:', jsonFile);
    console.error('Please run tests first to generate the report.');
    process.exit(1);
  }

  // Clean up old report files generated by multiple-cucumber-html-reporter
  const filesToClean = ['enriched-output.json', 'merged-output.json'];
  filesToClean.forEach(file => {
    const filePath = path.join(generatedDir, file);
    if (fs.existsSync(filePath)) {
      fs.removeSync(filePath);
    }
  });

  // Read JSON report to get metadata
  const jsonReport = fs.readJsonSync(jsonFile);
  
  // Calculate test statistics
  let totalScenarios = 0;
  let passedScenarios = 0;
  let failedScenarios = 0;
  let skippedScenarios = 0;
  
  jsonReport.forEach(feature => {
    feature.elements?.forEach(scenario => {
      totalScenarios++;
      const steps = scenario.steps || [];
      const hasFailed = steps.some(step => step.result.status === 'failed');
      const hasSkipped = steps.some(step => step.result.status === 'skipped');
      
      if (hasFailed) {
        failedScenarios++;
      } else if (hasSkipped) {
        skippedScenarios++;
      } else {
        passedScenarios++;
      }
    });
  });

  const currentDate = new Date().toISOString().split('T')[0];
  const currentTime = new Date().toLocaleTimeString();
  
  console.log('========================================');
  console.log('Generating HTML Report...');
  console.log('========================================');
  console.log(`Total Scenarios: ${totalScenarios}`);
  console.log(`✓ Passed: ${passedScenarios}`);
  console.log(`✗ Failed: ${failedScenarios}`);
  console.log(`⊘ Skipped: ${skippedScenarios}`);
  console.log('========================================');

  // Generate the report
  report.generate({
    jsonDir: path.join(process.cwd(), 'reports', 'generated'),
    reportPath: path.join(process.cwd(), 'reports', 'generated'),
    reportName: 'SauceDemo Automation Test Report',
    pageTitle: 'SauceDemo - Test Report',
    displayDuration: true,
    displayReportTime: true,
    durationInMS: false,
    hideMetadata: false,
    disableLog: false,
    openReportInBrowser: true,
    saveCollectedJSON: true,
    customMetadata: false,
    pageFooter: '<div style="text-align:center"><p>Automated with Playwright + Cucumber + TypeScript</p></div>',
    
    metadata: {
      browser: {
        name: process.env.BROWSER || 'chromium',
        version: 'latest',
      },
      device: 'Local Machine',
      platform: {
        name: process.platform,
        version: process.version,
      },
    },
    
    customData: {
      title: 'Test Execution Info',
      data: [
        { label: 'Project', value: 'SauceDemo E2E Testing' },
        { label: 'Test Type', value: 'Regression' },
        { label: 'Environment', value: process.env.BASE_URL || 'https://www.saucedemo.com' },
        { label: 'Execution Date', value: currentDate },
        { label: 'Execution Time', value: currentTime },
        { label: 'Total Scenarios', value: totalScenarios.toString() },
        { label: 'Passed', value: passedScenarios.toString() },
        { label: 'Failed', value: failedScenarios.toString() },
        { label: 'Pass Rate', value: `${((passedScenarios / totalScenarios) * 100).toFixed(2)}%` },
      ],
    },
    
    pageFooter: '<div style="text-align:center"><p>Automated with Playwright + Cucumber + TypeScript</p></div>',
  });

  console.log('========================================');
  console.log('✓ HTML Report Generated Successfully!');
  console.log('Location:', path.join(process.cwd(), 'reports', 'generated', 'index.html'));
  console.log('========================================');
}

// Execute report generation
try {
  generateReport();
} catch (error) {
  console.error('Failed to generate report:', error);
  process.exit(1);
}
